"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Download, FileSpreadsheet, LoaderCircle, Play, Upload } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type Job = { id: string; status: string; message: string; percent: number; total: number; completed: number; generated_rows: number; skipped_count: number; error_count: number; error?: string; summary?: Record<string, number>; depot_validation?: { row_count?: number; issues?: unknown[] } };
export default function StockTemplatePage() {
  const [job, setJob] = useState<Job | null>(null); const [error, setError] = useState("");
  const [uploading, setUploading] = useState(false); const [fileMessage, setFileMessage] = useState("");
  useEffect(() => { if (!job || !["queued", "running"].includes(job.status)) return; const timer = setInterval(async () => { const response = await fetch(`/api/stock/stock-template-status/${job.id}`, { cache: "no-store" }); const data = await response.json(); setJob(data); if (data.status === "error") setError(data.error || data.message); }, 1200); return () => clearInterval(timer); }, [job]);
  const start = async () => { setError(""); const response = await fetch("/api/stock/start-stock-template", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const data = await response.json(); if (!response.ok) return setError(data.error); setJob(data); };
  const uploadDepotFile = async (file: File) => { setUploading(true); setFileMessage(""); try { const form = new FormData(); form.append("file", file); const response = await fetch("/api/stock/depot-file", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const validation = data.validation || {}; const warnings = Number(validation.warning_count) || 0; setFileMessage(`${data.message} ${validation.row_count || 0} ürün satırı doğrulandı${warnings ? `, ${warnings} uyarı bulundu` : ""}.`); } catch (cause) { setFileMessage(cause instanceof Error ? cause.message : "Dosya yüklenemedi."); } finally { setUploading(false); } };
  const running = job && ["queued", "running"].includes(job.status); const done = job?.status === "done";
  return <main className="page-enter mx-auto max-w-6xl px-5 py-8 lg:px-8 lg:py-10"><PageHeading eyebrow="Ozon Operasyonu" title="Stok Şablonu" description="Depo tipi listesindeki tüm ürünleri IKEA mağazalarında sorgular ve Ozon’a yüklenebilir stok Excel dosyasını hazırlar." />
    <Card className="mb-6 flex flex-col gap-5 border-0 p-6 shadow-[0_12px_35px_rgba(15,23,42,.07)] sm:flex-row sm:items-center"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#fefeeb] text-[#101c33]"><FileSpreadsheet className="size-6" /></span><div className="min-w-0 flex-1"><h2 className="font-black text-slate-900">Depo Tipi Dosyası</h2><p className="mt-1 text-sm text-slate-500">Mevcut listeyi indirin, ürün ve depo tipi değişikliklerini yapıp tekrar yükleyin.</p>{fileMessage && <p className="mt-2 text-sm font-semibold text-blue-700">{fileMessage}</p>}</div><div className="flex shrink-0 flex-wrap gap-2"><Link href="/api/stock/depot-file" download prefetch={false}><Button variant="secondary" size="sm"><Download className="size-4" />Mevcut Dosyayı İndir</Button></Link><label className="inline-flex h-9 cursor-pointer items-center justify-center gap-2 rounded-xl bg-blue-700 px-3 text-sm font-semibold text-white transition hover:bg-blue-800 has-[:disabled]:pointer-events-none has-[:disabled]:opacity-50">{uploading ? <LoaderCircle className="size-4 animate-spin" /> : <Upload className="size-4" />}{uploading ? "Doğrulanıyor" : "Yeni Dosya Yükle"}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={uploading || Boolean(running)} className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadDepotFile(file); event.currentTarget.value = ""; }} /></label></div></Card>
    <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card className="border-0 p-7 shadow-[0_12px_35px_rgba(15,23,42,.07)]"><div className="flex items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-700"><FileSpreadsheet className="size-7" /></span><div><h2 className="text-lg font-black">Tüm ürünleri güncelle</h2><p className="mt-1 text-sm leading-6 text-slate-500">Depo Tipi.xlsx okunur, stok seviyeleri sorgulanır ve doğru 2/5 günlük depoya miktarlar atanır.</p></div></div><div className="mt-8"><div className="mb-2 flex justify-between text-xs font-bold"><span>{job?.message || "Başlamaya hazır"}</span><span>{job?.percent || 0}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-700 to-cyan-500 transition-all duration-500" style={{ width: `${job?.percent || 0}%` }} /></div>{running && <p className="mt-2 text-xs text-slate-500">{job.completed} / {job.total || "?"} ürün kodu işlendi</p>}</div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-7 flex gap-3"><Button onClick={() => void start()} disabled={Boolean(running)}>{running ? <LoaderCircle className="size-4 animate-spin" /> : <Play className="size-4" />}{running ? "Hazırlanıyor" : done ? "Yeniden Oluştur" : "Şablonu Oluştur"}</Button>{done && <a href={`/api/stock/stock-template-download/${job.id}`}><Button variant="secondary"><Download className="size-4" />Excel&apos;i İndir</Button></a>}</div></Card>
      <Card className="overflow-hidden border-0 bg-[#101c33] p-7 text-white shadow-[0_12px_35px_rgba(15,23,42,.12)]"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">İşlem sonucu</p>{done ? <><CheckCircle2 className="mt-6 size-10 text-emerald-400" /><p className="mt-4 text-2xl font-black">Şablon hazır</p><div className="mt-6 grid grid-cols-2 gap-4">{[["Ürün", job.summary?.product_count], ["Excel satırı", job.generated_rows], ["Stoklu ürün", job.summary?.positive_products], ["Atlanan", job.skipped_count]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-white/7 p-3"><p className="text-xl font-black">{value ?? 0}</p><p className="text-xs text-slate-400">{label}</p></div>)}</div></> : <><p className="mt-6 text-4xl font-black text-[#fefeeb]">4</p><p className="mt-1 text-sm font-bold">Ozon deposu otomatik yönetilir</p><ul className="mt-6 space-y-3 text-sm text-slate-300"><li>• UMT ExtraSmall / Express</li><li>• 2 ve 5 günlük teslimat</li><li>• Birleşik ürün bileşen kontrolü</li><li>• Hata ve atlanan satır raporu</li></ul></>}</Card></div>
  </main>;
}
