/* eslint-disable @next/next/no-img-element */
"use client";

import { useMemo, useRef, useState } from "react";
import { CircleStop, Download, FileDown, LoaderCircle, PackageCheck, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageHeading } from "@/components/page-heading";

type StockItem = { stock_code: string; product_name: string; entered_name: string; quantity: number; unit_price: number | null; line_total: number | null; image_url?: string; statuses: Record<string, string> };
type Result = { items: StockItem[]; skipped_lines: { line: number; text: string; reason: string }[] };
const stores = ["IKEA Ümraniye", "IKEA Kartal", "IKEA Bayrampaşa", "İnternet Mağazası"];
const sample = "801.521.55 Konserve Açacağı\t1\n305.229.22 Saklama Kabı\t2";

function money(value: number | null) { return value == null ? "—" : new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(value); }
function available(status?: string) { return status === "Var" || status === "Kritik"; }
function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

export default function StockPage() {
  const [text, setText] = useState(sample); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [filter, setFilter] = useState<"all" | "internet" | "none">("all"); const [quick, setQuick] = useState(false);
  const abortRef = useRef<AbortController | null>(null);
  const items = useMemo(() => (result?.items || []).filter((item) => filter === "internet" ? available(item.statuses["İnternet Mağazası"]) : filter === "none" ? stores.every((store) => !available(item.statuses[store])) : true), [result, filter]);
  const check = async () => { const controller = new AbortController(); abortRef.current = controller; setBusy(true); setError(""); try { const response = await fetch("/api/stock/check-order", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text, includeProductInfo: !quick }), signal: controller.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); setFilter("all"); } catch (cause) { setError(cause instanceof DOMException && cause.name === "AbortError" ? "Stok kontrolü durduruldu." : cause instanceof Error ? cause.message : "Stok sorgulanamadı."); } finally { if (abortRef.current === controller) abortRef.current = null; setBusy(false); } };
  const stop = () => { abortRef.current?.abort(); };
  const exportPdf = async () => { const response = await fetch("/api/stock/export-pdf", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items: result?.items || [], stores }) }); if (!response.ok) return setError((await response.json()).error); downloadBlob(await response.blob(), "siparis-stok.pdf"); };
  const exportExcel = () => { const rows = (result?.items || []).map((item) => [item.product_name, item.stock_code, item.quantity, item.unit_price ?? "", item.line_total ?? "", ...stores.map((s) => item.statuses[s] || "")]); const table = [["Ürün", "Kod", "Adet", "Birim fiyat", "Toplam", ...stores], ...rows].map((row) => `<tr>${row.map((cell) => `<td>${String(cell).replaceAll("&", "&amp;").replaceAll("<", "&lt;")}</td>`).join("")}</tr>`).join(""); downloadBlob(new Blob([`<meta charset="utf-8"><table>${table}</table>`], { type: "application/vnd.ms-excel" }), "siparis-stok.xls"); };
  const total = (result?.items || []).reduce((sum, item) => sum + (item.line_total || 0), 0);
  return <main className="page-enter mx-auto max-w-[1500px] px-5 py-8 lg:px-8 lg:py-10"><PageHeading eyebrow="Sipariş Operasyonu" title="Stok Kontrol" description="Sipariş listenizi toplu sorgulayın; mağaza uygunluklarını, fiyatları ve sipariş toplamını tek tabloda görün." />
    <Card className="overflow-hidden border-0 shadow-[0_12px_35px_rgba(15,23,42,.07)]"><div className="grid lg:grid-cols-[minmax(0,1fr)_300px]"><div className="p-6 lg:p-8"><label className="text-sm font-bold text-slate-800">Sipariş listesi</label><p className="mt-1 text-xs text-slate-500">Her satırda ürün kodu, ürün adı ve adet bulunabilir.</p><textarea value={text} onChange={(e) => setText(e.target.value)} className="mt-4 min-h-44 w-full resize-y rounded-2xl border border-slate-200 bg-slate-50 p-4 font-mono text-sm leading-7 outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100" />{error && <p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><Button onClick={() => void check()} disabled={busy || !text.trim()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />}{busy ? "Sorgulanıyor" : "Stokları Kontrol Et"}</Button>{busy && <Button variant="secondary" onClick={stop}><CircleStop className="size-4" />Durdur</Button>}<label className="flex items-center gap-2 text-sm font-medium text-slate-600"><input type="checkbox" checked={quick} onChange={(e) => setQuick(e.target.checked)} className="size-4 accent-blue-700" />Hızlı mod (ürün bilgisi alma)</label></div></div><div className="bg-[#101c33] p-6 text-white lg:p-8"><PackageCheck className="size-8 text-[#fefeeb]" /><p className="mt-5 text-xs font-bold uppercase tracking-widest text-slate-400">Sipariş özeti</p><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-1"><div><p className="text-3xl font-black">{result?.items.length || 0}</p><p className="text-xs text-slate-400">benzersiz ürün</p></div><div><p className="text-2xl font-black">{money(total)}</p><p className="text-xs text-slate-400">tahmini toplam</p></div></div></div></div></Card>
    {result && <section className="mt-7"><div className="mb-4 flex flex-wrap items-center gap-2"><button onClick={() => setFilter("all")} className={`rounded-full px-4 py-2 text-xs font-bold ${filter === "all" ? "bg-[#101c33] text-white" : "bg-white text-slate-600"}`}>Tümü ({result.items.length})</button><button onClick={() => setFilter("internet")} className={`rounded-full px-4 py-2 text-xs font-bold ${filter === "internet" ? "bg-[#101c33] text-white" : "bg-white text-slate-600"}`}>İnternette var</button><button onClick={() => setFilter("none")} className={`rounded-full px-4 py-2 text-xs font-bold ${filter === "none" ? "bg-[#101c33] text-white" : "bg-white text-slate-600"}`}>Hiçbir yerde yok</button><div className="ml-auto flex gap-2"><Button variant="secondary" size="sm" onClick={exportExcel}><Download className="size-4" />Excel</Button><Button variant="secondary" size="sm" onClick={() => void exportPdf()}><FileDown className="size-4" />PDF</Button></div></div><Card className="overflow-x-auto"><table className="w-full min-w-[1050px] border-collapse text-left text-sm"><thead><tr className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><th className="p-4">Ürün</th><th className="p-4">Adet</th><th className="p-4">Fiyat</th>{stores.map((s) => <th key={s} className="p-4">{s.replace("IKEA ", "")}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.stock_code} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="p-4"><div className="flex items-center gap-3">{item.image_url ? <img src={item.image_url} alt="" className="size-12 rounded-xl border object-contain" /> : <span className="size-12 rounded-xl bg-slate-100" />}<div><p className="max-w-sm font-bold text-slate-900">{item.product_name || item.entered_name}</p><p className="mt-0.5 font-mono text-xs text-slate-500">{item.stock_code}</p></div></div></td><td className="p-4 font-bold">{item.quantity}</td><td className="p-4"><p className="font-bold">{money(item.line_total)}</p><p className="text-xs text-slate-400">{money(item.unit_price)} / adet</p></td>{stores.map((store) => { const status = item.statuses[store] || "Hata"; return <td key={store} className="p-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${status === "Var" ? "bg-emerald-100 text-emerald-700" : status === "Kritik" ? "bg-amber-100 text-amber-700" : "bg-red-50 text-red-600"}`}>{status}</span></td>; })}</tr>)}</tbody></table>{items.length === 0 && <p className="p-10 text-center text-sm text-slate-500">Bu filtreye uygun ürün yok.</p>}</Card>{result.skipped_lines.length > 0 && <p className="mt-3 text-xs text-amber-700">{result.skipped_lines.length} satır ürün kodu bulunamadığı için atlandı.</p>}</section>}
  </main>;
}
