"use client";

import { useState } from "react";
import { FileCheck2, FileSpreadsheet, LoaderCircle, Tags, UploadCloud } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

function FileDrop({ label, hint, accept, file, onChange, icon: Icon }: { label: string; hint: string; accept: string; file: File | null; onChange: (file: File | null) => void; icon: typeof FileSpreadsheet }) { return <label className="group flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-6 text-center transition hover:border-blue-400 hover:bg-blue-50/50"><span className="grid size-12 place-items-center rounded-2xl bg-white text-blue-700 shadow-sm"><Icon className="size-6" /></span><span className="mt-4 text-sm font-black text-slate-800">{file?.name || label}</span><span className="mt-1 text-xs text-slate-500">{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB` : hint}</span><input className="sr-only" type="file" accept={accept} onChange={(e) => onChange(e.target.files?.[0] || null)} /></label>; }
export default function LabelsPage() {
  const [order, setOrder] = useState<File | null>(null); const [labels, setLabels] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async () => { if (!order || !labels) return; setBusy(true); setError(""); try { const form = new FormData(); form.append("order", order); form.append("labels", labels); const response = await fetch("/api/labels", { method: "POST", body: form }); if (!response.ok) throw new Error((await response.json()).error); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${new Date().toLocaleDateString("tr-TR").replaceAll(".", "-")}-yazili-etiketler.pdf`; a.click(); URL.revokeObjectURL(url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Etiket dosyası hazırlanamadı."); } finally { setBusy(false); } };
  return <main className="page-enter mx-auto max-w-6xl px-5 py-8 lg:px-8 lg:py-10"><PageHeading eyebrow="Sevkiyat Operasyonu" title="Etiket Yazdır" description="Sipariş listesindeki ürünleri sevkiyat numaralarıyla eşleştirir, kısa ürün kodlarını PDF etiketlerin altına ekler ve yazdırmaya hazır dosyayı indirir." />
    <Card className="border-0 p-6 shadow-[0_12px_35px_rgba(15,23,42,.07)] lg:p-8"><div className="grid gap-5 md:grid-cols-2"><FileDrop label="Sipariş listesini seçin" hint="XLSX veya CSV" accept=".xlsx,.csv" file={order} onChange={setOrder} icon={FileSpreadsheet} /><FileDrop label="Etiket PDF'ini seçin" hint="PDF dosyası" accept=".pdf" file={labels} onChange={setLabels} icon={Tags} /></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-6 flex flex-col justify-between gap-4 border-t border-slate-100 pt-6 sm:flex-row sm:items-center"><div className="flex items-center gap-3 text-sm text-slate-500"><FileCheck2 className="size-5 text-emerald-600" /><span>Kısa ürün kodu eşlemesi ve etiket sıralaması otomatik uygulanır.</span></div><Button onClick={() => void submit()} disabled={!order || !labels || busy} className="shrink-0">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <UploadCloud className="size-4" />}{busy ? "PDF hazırlanıyor" : "Etiketleri Hazırla"}</Button></div></Card>
    <div className="mt-6 grid gap-4 sm:grid-cols-3">{[["1", "Dosyaları yükleyin", "Sipariş listesi ile ham etiket PDF'i"], ["2", "OMEGA eşleştirsin", "Sevkiyat ve kısa ürün kodları otomatik bulunur"], ["3", "PDF'i indirin", "Sıralı ve yazdırmaya hazır çıktı"]].map(([n, title, desc]) => <div key={n} className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-sm font-black text-blue-700">0{n}</span><p className="mt-2 text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{desc}</p></div>)}</div>
  </main>;
}
